CREATE DATABASE "calendar-app";

DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS  IDENTITY,
    username TEXT,
    email TEXT,
    city TEXT
);

DROP TABLE IF EXISTS events;
CREATE TABLE events
(
    id                 BIGSERIAL PRIMARY KEY,
    title              TEXT,
    from_timestamp     TIMESTAMP,
    to_timestamp       TIMESTAMP,
    event_type         TEXT,
    description        TEXT,
    color              TEXT,
    snooze             BOOLEAN,
    user_id            BIGINT,
    is_active          BOOLEAN,
    deletion_timestamp TIMESTAMP,
    creation_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_timestamp   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE events_id_seq
    START WITH 1
    INCREMENT BY 1;
